services:
  app:
    build:
      context: .
      dockerfile: ./htmx/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      eventstore:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/timetracker
      - EVENTSTORE_CONNECTION_STRING=esdb://eventstore:2113?tls=false
    volumes:
      - .:/app
      - /app/target
    command: cargo watch -x "run --bin htmx"

  # leptos-app:
  #   build:
  #     context: .  # Root context to access workspace
  #     dockerfile: ./leptos-ssr/Dockerfile
  #   ports:
  #     - "3333:3333"  # Your Leptos site-addr port
  #     - "3334:3334"  # Your reload-port for hot reloading
  #   depends_on:
  #     db:
  #       condition: service_started
  #     eventstore:
  #       condition: service_started
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db:5432/timetracker
  #     - EVENTSTORE_CONNECTION_STRING=esdb://eventstore:2113?tls=false
  #     - LEPTOS_SITE_ADDR=0.0.0.0:3333  # Important: use 0.0.0.0 instead of 127.0.0.1
  #     - LEPTOS_RELOAD_PORT=3334
  #   volumes:
  #     - .:/app
  #     - /app/target
      
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timetracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore_data:/var/lib/eventstore

volumes:
  postgres_data:
  eventstore_data:
